### ISSUE TITLE
Unknown column 'tabBank Account.bank_ac_no'

### ISSUE THREAD

**Issue by barredterra** [alyf-de/banking#135]
```
Traceback (most recent call last):
  File "apps/banking/banking/klarna_kosma_integration/utils.py", line 244, in create_bank_transactions
    transaction_created = new_bank_transaction(account, transaction)
  File "apps/banking/banking/klarna_kosma_integration/utils.py", line 308, in new_bank_transaction
    new_transaction.submit()
  File "apps/frappe/frappe/model/document.py", line 1018, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 999, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 310, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 362, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1101, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 931, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1283, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1265, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 928, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/bank_transaction/bank_transaction.py", line 20, in on_submit
    self.auto_set_party()
  File "apps/erpnext/erpnext/accounts/doctype/bank_transaction/bank_transaction.py", line 165, in auto_set_party
    ).match()
  File "apps/erpnext/erpnext/accounts/doctype/bank_transaction/auto_match_party.py", line 26, in match
    ).match()
  File "apps/erpnext/erpnext/accounts/doctype/bank_transaction/auto_match_party.py", line 48, in match
    result = self.match_account_in_party()
  File "apps/erpnext/erpnext/accounts/doctype/bank_transaction/auto_match_party.py", line 58, in match_account_in_party
    party_result = frappe.db.get_all(
  File "apps/frappe/frappe/database/database.py", line 810, in get_all
    return frappe.get_all(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1938, in get_all
    return get_list(doctype, *args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1910, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 190, in execute
    result = self.build_and_run()
  File "apps/frappe/frappe/model/db_query.py", line 231, in build_and_run
    return frappe.db.sql(
  File "apps/frappe/frappe/database/database.py", line 244, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'tabBank Account.bank_ac_no' in 'where clause'")

```

Probably a Bug in ERPNext

**Comment by barredterra** [comment]
https://github.com/frappe/erpnext/pull/44416

**Comment by barredterra** [comment]
My PR only added better error handling. We should probably still investigate the root cause of the original error.

**Comment by marination** [comment]
@barredterra `or_filters["bank_ac_no"]` gets set for "Employee" and then when the loop moves on to the next party type, this value persists, since `or_filters` is instantiated outside the loop and does not get refreshed
Its written messily. I'll clean it up tomorrow
